version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: helpampmdb
      MYSQL_USER: helpmampm_user
      MYSQL_PASSWORD: Admin@123
    volumes:
      - prod_db:/var/lib/mysql
    ports:
      - "3301:3306"

  mysqlexporter:
    image: prom/mysqld-exporter
    volumes:
      - ./mysqlexporter/.my.cnf:/root/.my.cnf
    depends_on:
      - mysqldb
    environment:
      - "DATA_SOURCE_NAME=root:Admin@123@tcp(mysqldb:3306)/helpampmdb"
    ports:
      - "9104:9104"
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana
    ports:
      - "3000:3000"
    user: '104'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
  prometheus:
    depends_on:
      - app
    build: ./prometheus
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  app:
    links:
      - mysqldb
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/helpampmdb?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "Admin@123",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
      - ./logs:/home/ec2-user/logs
    stdin_open: true
    tty: true
networks:
  helpampm_docker-network:
volumes:
  prod_db:
  prometheus_data: { }
  grafana_data: { }
