name: helpampm
description: HELP-AM-PM

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.10+2

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  connectivity_plus: ^3.0.2
  flutter_bloc: ^8.1.1
  email_validator: ^2.1.17
  dio: ^4.0.6
  device_info_plus: ^8.0.0
  url_launcher: ^6.1.9
  image_picker: ^0.8.6
  flutter_image_compress: ^1.1.3
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.5
  location: ^4.4.0
  geolocator: ^9.0.2
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  http: ^0.13.5
  collection: ^1.16.0
  flutter_rating_bar: ^4.0.1
  flutter_calendar_carousel: ^2.4.1
  geocoding: ^2.0.5
  flutter_polyline_points: ^1.0.0
  country_list_pick: ^1.0.1+6
  getwidget: ^3.0.1
  syncfusion_flutter_pdf:
  firebase_core: ^2.6.1
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^13.0.0
  flutter_stripe: ^6.0.0
  google_places_flutter: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/mock_response/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
