name: API CI

on:
  push:
    paths:
      - 'help-am-pm-mothership-master/helpampm-api/**'
  pull_request:
    paths:
      - 'help-am-pm-mothership-master/helpampm-api/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build & test
        working-directory: help-am-pm-mothership-master/helpampm-api
        run: ./mvnw clean verify

      - name: Smoke-test health endpoint
        run: |
          sleep 10
          curl --fail http://localhost:8080/actuator/health 